server:
  port: 8080

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size:
        5000MB
      max-request-size:
        10000MB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.132:3306/digital_department?serverTimezone=Asia/Shanghai
    username: atcdi
    password: atcdi

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.atcdi.digital.handler


